image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
tasks:
  - init: npm i
    command: node lookUpZelda.js
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: true
