image:
  file: .gitpod.Dockerfile
tasks:
  - name: Server
    init: scripts/prebuild.sh
    command: cargo run
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
vscode:
  extensions:
    - webfreak.debug@0.24.0:1zVcRsAhewYEX3/A9xjMNw==
