CREATE TABLE IF NOT EXISTS USER (
    NAME TEXT UNIQUE,
    AGE INTEGER
);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Sean', 16);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Teddy', 17);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Josh', 17);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Christian', 16);


-- SELECT * FROM user;
