CREATE TABLE IF NOT EXISTS USER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE,
    AGE INTEGER
);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Sean', 16);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Teddy', 17);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Josh', 17);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES ('Christian', 16);
SELECT NAME, AGE FROM USER;
