CREATE TABLE IF NOT EXISTS USER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL,
    AGE INTEGER NOT NULL
);
INSERT OR IGNORE INTO USER (NAME, AGE) VALUES 
    ('Sean', 16),
    ('Teddy', 17),
    ('Josh', 17),
    ('Christian', 16),
    ('Max', 17);
